FILENAME = main.c
EXENAME = SimplePlatformer
install:
	cc $(FILENAME) -o $(EXENAME) -O1 -Wall -std=c99 -Wno-missing-braces -w -lSDL2

debug:
	cc -g $(FILENAME) -o $(EXENAME) -O1 -Wall -std=c99 -Wno-missing-braces -w -lSDL2

clean:
	rm $(EXENAME) 

