install:
	# cc -o Lesson2 main.c -lraylib -lGL -lm -lpthread -ldl -lrt -lX11
	cc main.c -o Lesson2 -O1 -Wall -std=c99 -Wno-missing-braces -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

clean:
	rm Lesson2
